### ISSUE TITLE
Project Page: Add Related Content

### ISSUE THREAD

**Issue by lsweltz** [InterActionNGO/ngoaidmap#20]
On the project page:

- Add a “Related Files” section that displays a list of URLs that link to external files.
- Place content in the main content well below other page content but above the featured maps section.

**Comment by RBFraxinus** [comment]
Instead of "Related Files", can you name it "Related Resources".
Also, regarding placement, can you make it show just above the "Other Projects" section at the bottom of the project data (project page attached).
![firefox_screenshot_2016-08-29t14-51-44 004z](https://cloud.githubusercontent.com/assets/14912412/18055622/9fa27738-6dd6-11e6-9794-754aa67355fb.png)
